export const FONT_OPTIONS = [
  "League Spartan",
  "Inter",
  "Poppins",
  "Montserrat",
  "Raleway",
  "Open Sans",
  "Lato",
  "Roboto",
  "Nunito",
  "Work Sans",
  "Quicksand",
  "Comfortaa",
  "Baloo 2",
  "Fredoka",
  "Chewy",
  "Pacifico",
  "Caveat",
  "Patrick Hand",
];

export const SECTION_LABELS: Record<string, string> = {
  "SiteSettings.json": "Site Settings",
  "HomePage.json": "Page Settings",
  "CompanySettings.json": "Company Settings",
  "Navigation.json": "Navigation",
  "HeroSection.json": "Home Page (Hero)",
  "ServiceCardsSection.json": "Services",
  "VideoSection.json": "Featured Video",
  "WhyChooseSection.json": "Why Choose Us",
  "CaseStudiesSection.json": "Case Studies",
  "HowSection.json": "How It Works",
  "TestimonialsSection.json": "Testimonials Carousel",
  "FaqSection.json": "Solar Guide",
  "AccreditationsSection.json": "Accreditations",
  "NewsVideosSection.json": "News & Videos",
  "LocationsSection.json": "Locations / Service Areas",
  "FinalCtaSection.json": "Final CTA",
  "Footer.json": "Footer",
  "TrustBarSection.json": "Trust Bar",
  "ImpactSection.json": "Impact Section",
  "pages/AboutPage.json": "About / Who We Are",
  "pages/SolarPanelsPage.json": "Solar Panels",
  "pages/UnderfloorHeatingPage.json": "Underfloor Heating",
  "pages/HeatPumpsPage.json": "Heat Pumps",
  "pages/BatteryStoragePage.json": "Battery Storage",
  "pages/EvChargersPage.json": "EV Chargers",
  "pages/CommercialSolarPage.json": "Commercial Solar",
  "pages/GrantsPage.json": "Grants",
  "pages/FinancePage.json": "Finance",
  "pages/FundingOptionsPage.json": "Funding Options",
  "pages/ContactPage.json": "Contact Page",
  "pages/TestimonialsPage.json": "Testimonials Page",
  "pages/PrivacyPolicyPage.json": "Privacy Policy Page",
  "pages/CookiesPage.json": "Cookies Page",
  "pages/CustomPages.json": "Custom Pages",
  "seo.json": "SEO Settings",
};

export const SECTION_GROUPS: { label: string; files: string[] }[] = [
  {
    label: "Top Level Settings",
    files: [
      "SiteSettings.json",
      "CompanySettings.json",
      "HomePage.json",
      "pages/CustomPages.json",
      "Navigation.json",
      "seo.json",
    ],
  },
  {
    label: "Hero Content",
    files: [
      "HeroSection.json",
      "ServiceCardsSection.json",
      "VideoSection.json",
      "WhyChooseSection.json",
      "HowSection.json",
      "CaseStudiesSection.json",
      "TestimonialsSection.json",
      "pages/TestimonialsPage.json",
      "FaqSection.json",
      "AccreditationsSection.json",
      "NewsVideosSection.json",
      "LocationsSection.json",
      "FinalCtaSection.json",
      "Footer.json",
    ],
  },
  {
    label: "Content Pages",
    files: [
      "pages/SolarPanelsPage.json",
      "pages/BatteryStoragePage.json",
      "pages/EvChargersPage.json",
      "pages/UnderfloorHeatingPage.json",
      "pages/HeatPumpsPage.json",
      "pages/CommercialSolarPage.json",
      "pages/AboutPage.json",
      "pages/GrantsPage.json",
      "pages/FinancePage.json",
      "pages/FundingOptionsPage.json",
      "pages/ContactPage.json",
      "pages/PrivacyPolicyPage.json",
      "pages/CookiesPage.json",
    ],
  },
];

export const SECTION_ORDER = SECTION_GROUPS.flatMap((g) => g.files);

export const ORDER_SECTION_LABELS: Record<string, string> = {
  hero: "Hero Section Settings",
  serviceCards: "Service Cards",
  video: "Featured Video",
  whyChoose: "Why Choose Us",
  caseStudies: "Case Studies",
  how: "How It Works",
  testimonials: "Testimonials Carousel",
  testimonialsPage: "Testimonials Page",
  faq: "Solar Guide",
  accreditations: "Accreditations",
  newsVideos: "News & Videos",
  finalCta: "Final CTA",
};

export const NON_ORDERABLE_SECTIONS = new Set(["navigation", "footer", "impact", "trustBar"]);

export const FIELD_LABEL_OVERRIDES: Record<string, string> = {
  "enabled": "Enabled",
  "hero": "Hero Section Settings",
  "heroAlignment": "Hero Headline Alignment",
  "heroLayout": "Desktop Layout",
  "mobileLayout": "Phone Layout",
  "wordWrapHeadlines": "Word Wrap Headlines",
  "showOnMobile": "Show on Mobile",
  "heroBadges": "Badges",
  "stats": "Stats",
  "style": "Card Style",
  "children": "Sub-Links",
  "mobileLabel": "Mobile Label",
  "links": "Navigation Items",
  "utilityLinks": "Utility Bar Links",
  "socialLinks": "Social Links",
  "showIcons": "Show Menu Icons",
  "title1": "Title 1",
  "title2": "Title 2",
  "section1": "Section 1 — Home Charging",
  "section2": "Section 2 — Commercial",
  "gtmId": "Google Tag Manager ID",
  "bannerImage": "Banner Background Image",
  "primaryColor": "Primary Color",
  "primaryDark": "Primary Dark Color",
  "accentColor": "Accent Color",
  "bannerOverlay": "Banner Overlay Color",
  "quoteButtonColor": "Quote Button Color",
  "contactButtonColor": "Contact Button Color",
  "emailNotifications": "Email Notifications",
  "smtpHost": "SMTP Server",
  "smtpPort": "SMTP Port",
  "smtpUser": "SMTP Username",
  "notifyEmail": "Send Notifications To",
  "fromEmail": "Send From Email",
  "fromName": "Send From Name",
  "locations": "📍 Locations",
  "highlights": "Key Stats",
  "newsItems": "📰 News",
  "videoItems": "🎬 Videos",
  "pages": "Custom Pages",
  "slug": "URL Path (e.g. new-service)",
  "type": "Page Type",
  "placement": "Placement",
  "iframeUrl": "iFrame URL",
  "imageUrl": "Image URL",
  "companyName": "Company Name",
  "openingHours": "Opening Hours",
  "line1": "Address Line 1",
  "line2": "Address Line 2",
  "county": "County / Region",
};

export const EMPTY_ARRAY_TEMPLATES: Record<string, Record<string, unknown>> = {
  pages: {
    enabled: true,
    slug: "",
    type: "section",
    placement: "page",
    iframeUrl: "",
    imageUrl: "",
    hero: {
      eyebrow: "",
      title: "",
      subtitle: "",
      bannerImage: "",
    },
    content: {
      eyebrow: "",
      title: "",
      cards: [],
    },
  },
  cards: {
    subHeading: "",
    paragraph: "",
    image: "",
  },
  socialLinks: {
    label: "",
    href: "",
  },
  locations: {
    slug: "",
    name: "",
    title: "",
    description: "",
    image: "",
    services: [],
    highlights: [],
  },
  highlights: {
    value: "",
    label: "",
  },
};

export const RICH_TEXT_PATH_PATTERNS = [
  /\.summary$/,
  /\.content$/,
  /\.answer$/,
  /\.description$/,
  /\.desc$/,
  /\.paragraph$/,
  /\.body$/,
  /\.text$/,
  /paragraphs\.\d+$/,
];

export const VALID_FILES = [
  "home/CompanySettings.json",
  "home/HeroSection.json",
  "home/Navigation.json",
  "home/Footer.json",
  "home/ServiceCardsSection.json",
  "home/TestimonialsSection.json",
  "home/FaqSection.json",
  "home/FinalCtaSection.json",
  "home/HomePage.json",
  "home/VideoSection.json",
  "home/CaseStudiesSection.json",
  "home/HowSection.json",
  "home/WhyChooseSection.json",
  "home/AccreditationsSection.json",
  "home/NewsVideosSection.json",
  "home/LocationsSection.json",
  "home/TrustBarSection.json",
  "home/ImpactSection.json",
  "pages/AboutPage.json",
  "pages/SolarPanelsPage.json",
  "pages/UnderfloorHeatingPage.json",
  "pages/HeatPumpsPage.json",
  "pages/BatteryStoragePage.json",
  "pages/EvChargersPage.json",
  "pages/CommercialSolarPage.json",
  "pages/GrantsPage.json",
  "pages/FinancePage.json",
  "pages/FundingOptionsPage.json",
  "pages/ContactPage.json",
  "pages/TestimonialsPage.json",
  "pages/PrivacyPolicyPage.json",
  "pages/CookiesPage.json",
  "pages/CustomPages.json",
  "seo.json",
  "home/SiteSettings.json",
  "home/HeaderSettings.json",
];
